version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    reviewers:
    - "dweinholz"
    - "tensulin"
    - "eKatchko"
    - "vktrrdk"
  open-pull-requests-limit: 10
  target-branch: master
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
    - "dweinholz"
    - "tensulin"
    - "eKatchko"
    - "vktrrdk"
  open-pull-requests-limit: 10
  target-branch: master
