version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: feat/dependabot
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  default_reviewers:
    - "dweinholz"
    - "tensulin"
    - "eKatchko"
    - "vktrrdk"
  open-pull-requests-limit: 10
  target-branch: master
