version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
      - "deNBI/portal-dev"
  commit-message:
      prefix: "feat"
      include: "scope"
  open-pull-requests-limit: 15
  target-branch: master
  
  
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
     - "deNBI/portal-dev"
  commit-message:
      prefix: "feat"
      include: "scope"
  open-pull-requests-limit: 15
  target-branch: master
