name: Create Release Image
on:
  push:
    tags:
      - '*'
jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
     - name: Get the version
       id: get_version
       run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
     - uses: actions/checkout@master
     - name: Publish to Registry
       uses: elgohr/Publish-Docker-Github-Action@master
       env:
          REPOSITORY: https://github.com/deNBI/cloud-user-docs/archive/master.tar.gz  
       with:
        name: denbicloud/mkdocsWebhook
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        buildargs: REPOSITORY  
        tags: ${{ steps.get_version.outputs.VERSION }}
     - name: Publish Staging to Registry
       uses: elgohr/Publish-Docker-Github-Action@master
       env:
          REPOSITORY: https://github.com/deNBI/cloud-user-docs/archive/master.tar.gz  
       with:
        name: denbicloud/mkdocswebhook
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        buildargs: REPOSITORY  
        tags: ${{ steps.get_version.outputs.VERSION }}-staging
