name: Publish Docker
on: 
  push:
    branches: 
      - 'staging'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow run cleanup action
      uses: rokroskar/workflow-run-cleanup-action@v0.3.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        REPOSITORY: https://github.com/deNBI/cloud-user-docs/archive/master.tar.gz
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        buildargs: REPOSITORY  
        tags: quay.io/denbicloud/mkdocswebhook:staging

