name: Publish Docker
on: 
  push:
    branches: 
      - 'staging'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow run cleanup action
      uses: rokroskar/workflow-run-cleanup-action@v0.3.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@master
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
    - name: Build and publish image to Quay
      uses: docker/build-push-action@v4
      env:
          REPOSITORY: https://github.com/deNBI/cloud-user-docs/archive/staging.tar.gz  
      with:
          file: Dockerfile
          push: true
          build-args: REPOSITORY
          tags: quay.io/denbicloud/mkdocswebhook:staging

